language: python
python:
- '2.7'
- '3.6'
script: ./setup.py sdist bdist_wheel
deploy:
    provider: pypi
    user: Nonymus   
    server: https://testpypi.python.org/pypi
    distributions: 'sdist bdist_wheel'
secure: "tI3IBQ2LZi0t83CpOETbkC7pOwYYyNltq26f/mTBd/zwoK+V46PEDIEv2QEVp/EQW+58QkS2ffnNuEk9EjN8bLEgeULjjG+FpAskRFKDbka/lsNrvD+0eLUjmWQyhujLoyNrLCdpeaT10CMZREE/pbbI1QEAqSMId1h7mm/qCSgJYLr6D0Bi4fJGAoGZDiKHK0V37CCWq7QtlGeS4ubPTj0OnHrLBvGtoRrp5YBPq3IMwckeiYs5uesnzFn60vwLONC1nSxPXiASc12cUw+WkyMoMkN5LvGqucFvrGH/SmLoebneYc/ylTySogbTFnjV6WmdbpQXjvdSObxnXZDa3635/1BNeE+uZMHXbnGyg89/rZfBSuq2pC5HFk77ZX2vjMkYC/+gHoaeBQ0OEn0nGlSebPLIjCO+c+MiBNocIIlZo/EBnKa9pr0besA5Y8LROgMUeXx423YKMnTqIsLp3TU9iVBYjNAbpMvV1Xjw8ruqluaLkq3Q3f7gh4FOnrZM6m3WjQCOUUtBzSIbt7y+xPFoHdFzF5zNivn4ADkLmjlJVOTFLyJHnoh77K+s276R6RKpMw3qwpYO5m+b4nJrG8kMgUw0VygoaGjCI1Eaa6M/NCIy0+T22vf3g1kq1AQZa5BEU0RYOFWhK6shboEWblZS+WvF9j1BSV+OegE7lOs="
